# Generated by Django 4.0.4 on 2022-04-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='responseType',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'yes/no'), (2, 'text'), (3, 'numberic')], default=2),
        ),
    ]
